import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import "./globals.css";
import DefaultLayout from "@/app/components/DefaultLayout/page";

const baloo = Baloo_2({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={baloo.className}>
        {/* Dùng DefaultLayout để bọc tất cả nội dung */}
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
